spring:
  application:
    name: account
  
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=false;trustServerCertificate=true
    username: sa
    password: ${MSSQL_SA_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        default_schema: top-secret
        format_sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

server:
  port: 8080
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    it.gov.mgs.account: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG